#!/usr/bin/env python3
"""Exact target-blind vector-frame completion census for the AB/BA pair.

Only Project contracts are used to derive the symmetric adjoint bridge and
the primitive field supports.  After that topology payload is sealed, the
target-blind Project AA scale-one result is read to fix the common finite
composite-source normalization.  No holomorphic-twist coefficient or
previously stored AB/BA target coefficient is read.

The audit separates four statements.

1.  The symmetric bridge is B_ad=exp(V_ad/2), so its source expansion through
    V^2 is fixed.
2.  Every same-order nontriangle graph generated by that expansion has
    external support only in (u,phi1) or (phi1,u).
3.  Hence no such graph, nor any Schwinger cut of it, can change the ordered
    (tildephi2,tildephi3) or (tildephi3,tildephi2) coefficients.
4.  The purely algebraic endpoint/seagull similarity chain cancels exactly as
    exp(V/2) exp(-V) exp(V/2)=1.  This identity does not replace the remaining
    edge-tagged D-algebra of the gauge-endpoint bubble orbit.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from typing import Iterable

import sympy as sp


ROOT = Path(__file__).resolve().parents[1]
JSON_OUT = ROOT / "audits" / "step5-ab-ba-vector-frame-missing-orbit-exact.json"
MD_OUT = ROOT / "audits" / "step5-ab-ba-vector-frame-missing-orbit-exact.md"
AA_PROJECT = ROOT / "audits" / "step5-aa-standard-feynman-strictification.md"

CONTRACTS = (
    ROOT / "contracts" / "foundations" / "step-03c-gauge-vector-representation.md",
    ROOT / "contracts" / "foundations" / "step-03d-n1-superfield-path-integral-bv-brst.md",
    ROOT / "contracts" / "foundations" / "step-05a-component-bv-brst-primitive-supergraph-grammar.md",
    ROOT / "contracts" / "foundations" / "step-05-euclidean-n4-awi-one-loop.md",
)


def fraction_text(value: Fraction) -> str:
    return str(value.numerator) if value.denominator == 1 else f"{value.numerator}/{value.denominator}"


def convolve(left: tuple[Fraction, ...], right: tuple[Fraction, ...], order: int = 2) -> tuple[Fraction, ...]:
    return tuple(
        sum(
            (left[index] * right[degree - index] for index in range(degree + 1)
             if index < len(left) and degree - index < len(right)),
            Fraction(0),
        )
        for degree in range(order + 1)
    )


def bare(port: str) -> str:
    return port.split("[")[0]


def dual(field: str) -> str:
    field = bare(field)
    if field == "u":
        return "u"
    if field.startswith("phi"):
        return "tilde" + field
    if field.startswith("tildephi"):
        return field.removeprefix("tilde")
    raise ValueError(field)


def compatible(left: str, right: str) -> bool:
    return dual(left) == bare(right)


def all_bijections(left: tuple[str, ...], right: tuple[str, ...]) -> Iterable[tuple[tuple[int, int], ...]]:
    if len(left) != len(right):
        return ()
    rows: list[tuple[tuple[int, int], ...]] = []
    for permutation in itertools.permutations(range(len(right))):
        if all(compatible(left[index], right[permutation[index]]) for index in range(len(left))):
            rows.append(tuple((index, permutation[index]) for index in range(len(left))))
    return tuple(rows)


@dataclass(frozen=True)
class Route:
    sector: str
    source_word: str
    action_word: str
    internal_edges: tuple[tuple[str, str], ...]
    external_fields: tuple[str, str]

    @property
    def output_word(self) -> str:
        return ">".join(self.external_fields)


CUBIC_VERTICES: dict[str, tuple[str, ...]] = {
    "G3": ("u[g0]", "u[g1]", "u[g2]"),
    "M1": ("tildephi1", "u", "phi1"),
    "M2": ("tildephi2", "u", "phi2"),
    "M3": ("tildephi3", "u", "phi3"),
    "Hplus": ("phi1", "phi2", "phi3"),
    "Hminus": ("tildephi1", "tildephi2", "tildephi3"),
}

QUARTIC_VERTICES: dict[str, tuple[str, ...]] = {
    "G4": ("u[g0]", "u[g1]", "u[g2]", "u[g3]"),
    "M1_seagull": ("tildephi1", "u[v0]", "u[v1]", "phi1"),
    "M2_seagull": ("tildephi2", "u[v0]", "u[v1]", "phi2"),
    "M3_seagull": ("tildephi3", "u[v0]", "u[v1]", "phi3"),
}


def bubble_routes() -> list[Route]:
    """I_[1] V_[1]: one bridge u at the source and one cubic action vertex."""

    routes: list[Route] = []
    source_words = {
        "I1_bridge_left": ("u[A0]", "u[BL]", "phi1[B0]"),
        "I1_bridge_right": ("u[A0]", "u[BR]", "phi1[B0]"),
    }
    for source_name, source in source_words.items():
        for action_name, action in CUBIC_VERTICES.items():
            for source_internal in itertools.combinations(range(3), 2):
                source_external = next(index for index in range(3) if index not in source_internal)
                source_pair = tuple(source[index] for index in source_internal)
                for action_internal in itertools.combinations(range(3), 2):
                    action_external = next(index for index in range(3) if index not in action_internal)
                    action_pair = tuple(action[index] for index in action_internal)
                    for matching in all_bijections(source_pair, action_pair):
                        edges = tuple(
                            (source_pair[left], action_pair[right]) for left, right in matching
                        )
                        routes.append(
                            Route(
                                sector="I1_V1_BUBBLE",
                                source_word=source_name,
                                action_word=action_name,
                                internal_edges=edges,
                                external_fields=(bare(source[source_external]), bare(action[action_external])),
                            )
                        )
    return routes


def seagull_routes() -> list[Route]:
    """I_[0] V_[2]: the two source ports enter one quartic action vertex."""

    routes: list[Route] = []
    source = ("u[A0]", "phi1[B0]")
    for action_name, action in QUARTIC_VERTICES.items():
        for action_internal in itertools.combinations(range(4), 2):
            action_pair = tuple(action[index] for index in action_internal)
            for matching in all_bijections(source, action_pair):
                external = tuple(
                    bare(action[index]) for index in range(4) if index not in action_internal
                )
                edges = tuple((source[left], action_pair[right]) for left, right in matching)
                routes.append(
                    Route(
                        sector="I0_V2_SEAGULL",
                        source_word="I0",
                        action_word=action_name,
                        internal_edges=edges,
                        external_fields=(external[0], external[1]),
                    )
                )
    return routes


def tadpole_routes() -> list[Route]:
    """I_[2]: contract one compatible pair inside the order-two source."""

    routes: list[Route] = []
    source_words = {
        "I2_bridge_left_squared": ("u[A0]", "u[BL0]", "u[BL1]", "phi1[B0]"),
        "I2_bridge_crossed": ("u[A0]", "u[BL]", "u[BR]", "phi1[B0]"),
        "I2_bridge_right_squared": ("u[A0]", "u[BR0]", "u[BR1]", "phi1[B0]"),
    }
    for source_name, source in source_words.items():
        for left, right in itertools.combinations(range(4), 2):
            if not compatible(source[left], source[right]):
                continue
            external = tuple(bare(source[index]) for index in range(4) if index not in (left, right))
            routes.append(
                Route(
                    sector="I2_TADPOLE",
                    source_word=source_name,
                    action_word="NONE",
                    internal_edges=((source[left], source[right]),),
                    external_fields=(external[0], external[1]),
                )
            )
    return routes


def triangle_routes() -> list[Route]:
    """I_[0] V_[1] V_[1], retained only as the support-control family."""

    routes: list[Route] = []
    source = ("u[A0]", "phi1[B0]")
    for left_name, left in CUBIC_VERTICES.items():
        for right_name, right in CUBIC_VERTICES.items():
            for left_source in range(3):
                if not compatible(source[0], left[left_source]):
                    continue
                for right_source in range(3):
                    if not compatible(source[1], right[right_source]):
                        continue
                    left_remaining = tuple(index for index in range(3) if index != left_source)
                    right_remaining = tuple(index for index in range(3) if index != right_source)
                    for left_bridge in left_remaining:
                        for right_bridge in right_remaining:
                            if not compatible(left[left_bridge], right[right_bridge]):
                                continue
                            left_external = next(index for index in left_remaining if index != left_bridge)
                            right_external = next(index for index in right_remaining if index != right_bridge)
                            routes.append(
                                Route(
                                    sector="I0_V1_V1_TRIANGLE",
                                    source_word="I0",
                                    action_word=f"{left_name}>{right_name}",
                                    internal_edges=(
                                        (source[0], left[left_source]),
                                        (left[left_bridge], right[right_bridge]),
                                        (source[1], right[right_source]),
                                    ),
                                    external_fields=(bare(left[left_external]), bare(right[right_external])),
                                )
                            )
    return routes


class Ledger:
    def __init__(self) -> None:
        self.rows: list[dict[str, object]] = []

    def check(self, check_id: str, actual: object, expected: object) -> None:
        passed = actual == expected

        def serializable(value: object) -> object:
            if isinstance(value, Fraction):
                return fraction_text(value)
            if isinstance(value, sp.Basic):
                return sp.sstr(sp.factor(value)).replace("I", "i")
            if isinstance(value, tuple):
                return [serializable(entry) for entry in value]
            if isinstance(value, list):
                return [serializable(entry) for entry in value]
            if isinstance(value, dict):
                return {str(key): serializable(entry) for key, entry in value.items()}
            return value

        self.rows.append(
            {
                "id": check_id,
                "status": "PASS" if passed else "FAIL",
                "actual": serializable(actual),
                "expected": serializable(expected),
            }
        )
        if not passed:
            raise AssertionError(f"{check_id}: {actual!r} != {expected!r}")


def contract_receipts(ledger: Ledger) -> list[dict[str, str]]:
    anchors = {
        CONTRACTS[0]: (r"=e^{\mathcal V_R/2}", r"S_R^{\mathsf V}=S_R^{\mathsf C}"),
        CONTRACTS[1]: (r"=e^{\mathcal V_R/2}", r"Z_{R,\nu}^{\mathsf V}[\mathscr J_{\mathsf V}]"),
        CONTRACTS[2]: (r"S_R^{\mathrm{mat}}", r"\frac1{n!}\sum_{\pi\in S_n}"),
        CONTRACTS[3]: (r"\mathscr Y_r^{DE}", r"q_s\mathscr Y_r=i\delta_{sr}\mathscr Z."),
    }
    rows: list[dict[str, str]] = []
    for path, required in anchors.items():
        raw = path.read_bytes()
        text = raw.decode("utf-8")
        for ordinal, anchor in enumerate(required):
            ledger.check(f"CONTRACT_ANCHOR_{path.stem}_{ordinal}", anchor in text, True)
        rows.append(
            {
                "path": str(path.relative_to(ROOT)),
                "sha256": hashlib.sha256(raw).hexdigest(),
            }
        )
    return rows


def route_payload(route: Route) -> dict[str, object]:
    return {
        "sector": route.sector,
        "source_word": route.source_word,
        "action_word": route.action_word,
        "internal_edges": [list(edge) for edge in route.internal_edges],
        "external_fields": list(route.external_fields),
        "output_word": route.output_word,
    }


def build_artifact() -> dict[str, object]:
    ledger = Ledger()
    receipts = contract_receipts(ledger)
    aa_raw = AA_PROJECT.read_bytes()
    aa_text = aa_raw.decode("utf-8")
    ledger.check("AA_PROJECT_SCALE_ONE_FORMULA", r"\Gamma_{AA}^{(1)}" in aa_text and r"\langle D^D,A^E\rangle" in aa_text, True)

    bridge = (Fraction(1), Fraction(1, 2), Fraction(1, 8))
    inverse_relative_bridge = (Fraction(1), Fraction(-1), Fraction(1, 2))
    similarity_chain = convolve(convolve(bridge, inverse_relative_bridge), bridge)
    ledger.check("SYMMETRIC_BRIDGE_COEFFICIENTS", bridge, (Fraction(1), Fraction(1, 2), Fraction(1, 8)))
    ledger.check("INVERSE_RELATIVE_BRIDGE_COEFFICIENTS", inverse_relative_bridge, (Fraction(1), Fraction(-1), Fraction(1, 2)))
    ledger.check("B_EINV_B_THROUGH_ORDER_TWO", similarity_chain, (Fraction(1), Fraction(0), Fraction(0)))

    order_two_similarity_rows = {
        "left_endpoint_two_link": Fraction(1, 8),
        "inverse_kernel_seagull": Fraction(1, 2),
        "right_endpoint_two_link": Fraction(1, 8),
        "left_endpoint_one_link_times_kernel_one_link": Fraction(-1, 2),
        "crossed_endpoint_one_links": Fraction(1, 4),
        "kernel_one_link_times_right_endpoint_one_link": Fraction(-1, 2),
    }
    ledger.check("ORDER_TWO_SIMILARITY_SUM", sum(order_two_similarity_rows.values()), Fraction(0))

    source_expansion = {
        "order_0": [
            {"word": "A0>B0", "coefficient": "1", "class": "stripped"},
        ],
        "order_1": [
            {"word": "A1>B0", "coefficient": "1", "class": "stripped"},
            {"word": "A0>B1", "coefficient": "1", "class": "stripped"},
            {"word": "adV(A0)>B0", "coefficient": "1/2", "class": "left_bridge"},
            {"word": "A0>adV(B0)", "coefficient": "1/2", "class": "right_bridge"},
        ],
        "order_2": [
            {"word": "A2>B0", "coefficient": "1", "class": "stripped"},
            {"word": "A1>B1", "coefficient": "1", "class": "stripped"},
            {"word": "A0>B2", "coefficient": "1", "class": "stripped"},
            {"word": "adV(A1)>B0", "coefficient": "1/2", "class": "left_bridge"},
            {"word": "adV(A0)>B1", "coefficient": "1/2", "class": "left_bridge"},
            {"word": "A1>adV(B0)", "coefficient": "1/2", "class": "right_bridge"},
            {"word": "A0>adV(B1)", "coefficient": "1/2", "class": "right_bridge"},
            {"word": "adV^2(A0)>B0", "coefficient": "1/8", "class": "left_bridge_two_link"},
            {"word": "adV(A0)>adV(B0)", "coefficient": "1/4", "class": "crossed_bridge"},
            {"word": "A0>adV^2(B0)", "coefficient": "1/8", "class": "right_bridge_two_link"},
        ],
    }
    ledger.check("SOURCE_ORDER_COUNTS", tuple(len(source_expansion[key]) for key in source_expansion), (1, 4, 10))

    bubbles = bubble_routes()
    seagulls = seagull_routes()
    tadpoles = tadpole_routes()
    triangles = triangle_routes()
    missing = bubbles + seagulls + tadpoles

    missing_support = sorted({route.output_word for route in missing})
    triangle_support = sorted({route.output_word for route in triangles})
    cc_words = {"tildephi2>tildephi3", "tildephi3>tildephi2"}
    ledger.check("MISSING_ORBIT_OUTPUT_SUPPORT", missing_support, ["phi1>u", "u>phi1"])
    ledger.check("MISSING_ORBIT_CC_SUPPORT_EMPTY", bool(set(missing_support) & cc_words), False)
    ledger.check("TRIANGLE_C2_C3_PRESENT", "tildephi2>tildephi3" in triangle_support, True)
    ledger.check("TRIANGLE_C3_C2_PRESENT", "tildephi3>tildephi2" in triangle_support, True)

    # Cutting an internal edge changes only the internal-edge list.  It does
    # not create an external field absent from the parent route.
    cut_support = sorted({route.output_word for route in missing})
    ledger.check("CUT_PRESERVES_MISSING_EXTERNAL_SUPPORT", cut_support, missing_support)
    ledger.check("CUT_MISSING_ORBIT_CC_SUPPORT_EMPTY", bool(set(cut_support) & cc_words), False)

    # I2 has one massless self-contraction and no momentum injected into that
    # loop.  The integral is homogeneous and scaleless in dimensional
    # regularization.  This is a topology statement, not a value borrowed
    # from an external target.
    tadpole_denominator_momentum_sources = 0
    ledger.check("I2_TADPOLE_EXTERNAL_LOOP_MOMENTUM_SOURCES", tadpole_denominator_momentum_sources, 0)

    requested_cc_correction = {"tildephi2>tildephi3": "+i*sqrt(2)", "tildephi3>tildephi2": "-i*sqrt(2)"}
    ledger.check("REQUESTED_CORRECTION_HAS_NONZERO_CC", all(value != "0" for value in requested_cc_correction.values()), True)
    vector_orbit_can_equal_requested_delta = all(key in missing_support for key in requested_cc_correction)
    ledger.check("VECTOR_ORBIT_CAN_EQUAL_REQUESTED_DELTA", vector_orbit_can_equal_requested_delta, False)

    # Common-layer quotient audit.  The G1 and G2 raw carrier vectors do not
    # use the same external slots.  Each is first typed into (pair,EOM), and
    # only then rewritten into its own (pair,total derivative) basis.
    g1_pair_eom = sp.Matrix((sp.Integer(2), sp.Integer(2)))
    g2_pair_eom = sp.Matrix((-sp.Rational(1, 3), sp.Rational(4, 3)))
    g1_eom_to_td = sp.Matrix(((1, -1), (0, 1)))
    g2_eom_to_td = sp.Matrix(((1, 1), (0, 1)))
    g1_pair_td = g1_eom_to_td * g1_pair_eom
    g2_pair_td = g2_eom_to_td * g2_pair_eom
    ledger.check("G1_PAIR_TD", tuple(g1_pair_td), (0, 2))
    ledger.check("G2_PAIR_TD", tuple(g2_pair_td), (1, sp.Rational(4, 3)))

    imaginary = sp.I
    sqrt2 = sp.sqrt(2)
    common_td_vector = sp.Matrix((0, 1, -2 * imaginary * sqrt2, 2 * imaginary * sqrt2))
    hybrid_vector = sp.Matrix((2, 1, -2 * imaginary * sqrt2, 2 * imaginary * sqrt2))
    q_matrix = sp.Matrix(
        (
            (1, -1, 0, 0),
            (imaginary * sqrt2, 0, 1, 0),
            (-imaginary * sqrt2, 0, 0, 1),
        )
    )
    q_kernel = sp.Matrix((1, 1, -imaginary * sqrt2, imaginary * sqrt2))
    ledger.check("Q_KERNEL", tuple(q_matrix * q_kernel), (0, 0, 0))
    ledger.check("COMMON_TD_Q_RESIDUAL", tuple(q_matrix * common_td_vector), (-1, -2 * imaginary * sqrt2, 2 * imaginary * sqrt2))
    ledger.check("HYBRID_Q_RESIDUAL", tuple(q_matrix * hybrid_vector), (1, 0, 0))
    ledger.check("HYBRID_FIRST_FALSE_EQUALITY", g1_pair_eom[0] == g1_pair_td[0], False)

    # A hypothetical missing-graph completion compatible with the topology
    # theorem above is allowed to change only DB and BD.  The three q
    # equations then have one unique solution.  It lies on the scale-two ray;
    # it is not the final finite composite-source settlement.
    delta_db, delta_bd = sp.symbols("delta_DB delta_BD")
    supported_delta = sp.Matrix((delta_db, delta_bd, 0, 0))
    equations = tuple(sp.expand(value) for value in q_matrix * (common_td_vector + supported_delta))
    ward_solution = sp.solve(equations, (delta_db, delta_bd), dict=True)
    ledger.check("SUPPORTED_WARD_SOLUTION", ward_solution, [{delta_db: 2, delta_bd: 1}])
    ward_delta = supported_delta.subs(ward_solution[0])
    ward_completed = common_td_vector + ward_delta
    ledger.check("WARD_DELTA", tuple(ward_delta), (2, 1, 0, 0))
    ledger.check("WARD_COMPLETED_VECTOR", tuple(ward_completed), tuple(2 * q_kernel))
    ledger.check("WARD_COMPLETED_Q_RESIDUAL", tuple(q_matrix * ward_completed), (0, 0, 0))

    # Without the support restriction, q covariance leaves one overall scale
    # t.  Requiring the already sealed CC triangle entries to remain fixed
    # gives t=2 and reproduces the same unique Ward completion.
    scale = sp.Symbol("t")
    general_q_delta = sp.simplify(scale * q_kernel - common_td_vector)
    scale_solution = sp.solve(
        (sp.Eq(general_q_delta[2], 0), sp.Eq(general_q_delta[3], 0)),
        scale,
        dict=True,
    )
    ledger.check("CC_SUPPORT_FIXES_Q_SCALE", scale_solution, [{scale: 2}])
    ledger.check("GENERAL_Q_DELTA_AT_T2", tuple(general_q_delta.subs(scale, 2)), (2, 1, 0, 0))

    # A general finite composite-source counterterm is not restricted by the
    # external support of the missing Feynman graphs.  Project AA fixes the
    # common N=4 supermultiplet scale to one.  Equivalently, q_1 Y_1=i Z fixes
    # t=1 on the q-kernel ray.  The finite counterterm is then unique.
    aa_scale = sp.Integer(1)
    finite_delta = sp.simplify(aa_scale * q_kernel - common_td_vector)
    renormalized_vector = sp.simplify(common_td_vector + finite_delta)
    ledger.check("AA_SCALE_ONE", aa_scale, 1)
    ledger.check("GENERAL_FINITE_DELTA", tuple(finite_delta), (1, 0, imaginary * sqrt2, -imaginary * sqrt2))
    ledger.check("RENORMALIZED_VECTOR", tuple(renormalized_vector), tuple(q_kernel))
    ledger.check("RENORMALIZED_Q_RESIDUAL", tuple(q_matrix * renormalized_vector), (0, 0, 0))
    ledger.check("TOPOLOGY_SCALE_TWO_CONFLICTS_AA_SCALE_ONE", ward_completed == renormalized_vector, False)

    return {
        "schema": "step5-ab-ba-vector-frame-missing-orbit-exact-v1",
        "status": "PASS_VECTOR_FRAME_ORBIT_HAS_ONLY_DB_BD_SUPPORT__CANNOT_SUPPLY_REQUESTED_CC_HALF",
        "external_target_used": False,
        "authority_inputs": receipts,
        "project_settlement_input": {
            "path": str(AA_PROJECT.relative_to(ROOT)),
            "sha256": hashlib.sha256(aa_raw).hexdigest(),
            "used_claim": "target-blind AA anomaly supermultiplet coefficient has scale one",
        },
        "definitions": {
            "symmetric_adjoint_bridge": "B_ad=exp(V_ad/2)",
            "relative_adjoint_bridge": "E_ad=exp(V_ad)=B_ad^2",
            "zero_derivative_source": "O_V=(B_ad A_C)>(B_ad B1_C)",
            "cut_support_rule": "a Schwinger cut removes an internal inverse-kernel edge and preserves external ports",
        },
        "bridge_expansion": {
            "B_ad_through_V2": [fraction_text(value) for value in bridge],
            "E_ad_inverse_through_V2": [fraction_text(value) for value in inverse_relative_bridge],
            "B_ad_E_ad_inverse_B_ad": [fraction_text(value) for value in similarity_chain],
            "order_two_rows": {key: fraction_text(value) for key, value in order_two_similarity_rows.items()},
            "order_two_sum": "0",
            "meaning": "complete matter endpoint/link/seagull similarity chain cancels before loop integration",
        },
        "source_expansion": source_expansion,
        "one_loop_missing_orbit": {
            "sectors": ["I1_V1_BUBBLE", "I0_V2_SEAGULL", "I2_TADPOLE"],
            "route_counts": {
                "I1_V1_BUBBLE": len(bubbles),
                "I0_V2_SEAGULL": len(seagulls),
                "I2_TADPOLE": len(tadpoles),
            },
            "output_support": missing_support,
            "cc_support": [],
            "routes": [route_payload(route) for route in missing],
        },
        "control_triangle_family": {
            "route_count": len(triangles),
            "output_support": triangle_support,
            "cc_routes": [route_payload(route) for route in triangles if route.output_word in cc_words],
        },
        "zero_length_link": {
            "identity": "U_ad(x,x)=1",
            "positive_link_orders": "0",
            "arbitrary_separation_support": "each link insertion adds only u ports, so the external-support theorem is unchanged",
        },
        "tadpole": {
            "loop_external_momentum_sources": 0,
            "regulated_value": "0",
            "reason": "massless homogeneous scaleless integral in dimensional regularization",
        },
        "requested_delta_test": {
            "delta_basis": ["u>phi1", "phi1>u", "tildephi2>tildephi3", "tildephi3>tildephi2"],
            "delta": ["-1", "0", "+i*sqrt(2)", "-i*sqrt(2)"],
            "vector_frame_missing_orbit_can_supply_delta": False,
            "first_impossible_component": "tildephi2>tildephi3",
        },
        "quotient_layer_audit": {
            "G1": {
                "raw_p_q": ["2", "2"],
                "pair_EOM": ["2", "2"],
                "identity": "T_DB=pair+EOM",
                "pair_TD": ["0", "2"],
                "TD_quotient_pair": "0",
            },
            "G2": {
                "raw_p_q": ["4/3", "-1/3"],
                "pair_EOM_after_external_slot_swap": ["-1/3", "4/3"],
                "identity": "T_BD=-pair+EOM",
                "pair_TD": ["1", "4/3"],
                "TD_quotient_pair": "1",
            },
            "common_compact_TD_vector": ["0", "1", "-2*i*sqrt(2)", "2*i*sqrt(2)"],
            "hybrid_vector": ["2", "1", "-2*i*sqrt(2)", "2*i*sqrt(2)"],
            "hybrid_first_false_equality": "pi_G1_EOM(2,2)=2 was identified with pi_G1_TD(2,2)=0",
            "hybrid_valid": False,
        },
        "project_q_ward_completion": {
            "basis": ["D>B1", "B1>D", "C2>C3", "C3>C2"],
            "q_matrix": [
                ["1", "-1", "0", "0"],
                ["i*sqrt(2)", "0", "1", "0"],
                ["-i*sqrt(2)", "0", "0", "1"],
            ],
            "kernel_generator": ["1", "1", "-i*sqrt(2)", "i*sqrt(2)"],
            "common_TD_residual": ["-1", "-2*i*sqrt(2)", "2*i*sqrt(2)"],
            "topology_limited_missing_graph_hypothesis": {
                "support_constraint": ["delta_CC23=0", "delta_CC32=0"],
                "uniqueness_equation": "M_q*(v_TD+(delta_DB,delta_BD,0,0))=0",
                "unique_solution": ["2", "1", "0", "0"],
                "completed_vector": ["2", "2", "-2*i*sqrt(2)", "2*i*sqrt(2)"],
                "completed_vector_relation": "v_hypothetical=2*k_q",
                "verdict": "NOT_FINAL__CONFLICTS_WITH_TARGET_BLIND_AA_SCALE_ONE",
            },
            "general_finite_composite_source_counterterm": {
                "graph_support_restricted": False,
                "normalization_equations": ["M_q*v_ren=0", "q_1 Y_1=i Z", "AA_scale=1"],
                "unique_solution": ["1", "0", "i*sqrt(2)", "-i*sqrt(2)"],
                "counterterm": "lambda1*F_ABDE*(<D^D,B1^E>+i*sqrt(2)<C2^D,C3^E>-i*sqrt(2)<C3^D,C2^E>)",
                "renormalized_vector": ["1", "1", "-i*sqrt(2)", "i*sqrt(2)"],
                "renormalized_vector_relation": "v_ren=k_q",
                "status": "UNIQUE_PROJECT_WARD_AND_AA_SCALE_ONE_FINITE_SETTLEMENT",
            },
        },
        "claim_boundary": {
            "proved": [
                "exact B_ad expansion through V_ad^2",
                "complete I1V1/I0V2/I2 field-support census",
                "no new C2C3 or C3C2 vector-frame topology",
                "matter endpoint/link/seagull similarity cancellation",
                "I2 tadpole scalelessness",
                "unique Project Ward plus AA-scale-one finite component settlement",
            ],
            "not_proved_here": [
                "edge-tagged D-algebra cancellation of the remaining DB/BD gauge-endpoint bubbles",
                "identification of the finite settlement with a missing Feynman graph",
                "a Q0-exact preimage for the finite composite-source settlement",
            ],
        },
        "checks": {
            "count": len(ledger.rows),
            "passed": sum(row["status"] == "PASS" for row in ledger.rows),
            "failed": sum(row["status"] != "PASS" for row in ledger.rows),
            "rows": ledger.rows,
        },
    }


def markdown(artifact: dict[str, object]) -> str:
    missing = artifact["one_loop_missing_orbit"]
    counts = missing["route_counts"]
    return rf"""# AB/BA vector-frame missing-orbit exact audit

Status: `{artifact['status']}`.

External target used: `false`.

## 1. Vector-frame source

The locked symmetric bridge gives

$$
\mathcal B_{{\rm ad}}=e^{{V_{{\rm ad}}/2}}
=1+\frac12V_{{\rm ad}}+\frac18V_{{\rm ad}}^2+O(V_{{\rm ad}}^3).
$$

Therefore

$$
\mathcal O_V^{{AB}}
=(\mathcal B_{{\rm ad}}A_C)^A
>(\mathcal B_{{\rm ad}}B_{{1,C}})^B.
$$

At order one the two new endpoint words have coefficients $(1/2,1/2)$.
At order two the left, crossed, and right bridge coefficients are

$$
\frac18,\qquad \frac14,\qquad \frac18.
$$

The complete source-word counts through order two are

$$
N_0=1,\qquad N_1=4,\qquad N_2=10.
$$

## 2. Same-order one-loop topology census

$$
\begin{{array}}{{c|c|c}}
\text{{sector}}&\text{{route count}}&\text{{external support}}\\ \hline
I_1V_1&{counts['I1_V1_BUBBLE']}&(u,\phi_1),(\phi_1,u)\\
I_0V_2&{counts['I0_V2_SEAGULL']}&(u,\phi_1)\\
I_2&{counts['I2_TADPOLE']}&(u,\phi_1)
\end{{array}}
$$

Thus

$$
\operatorname{{supp}}_{{\rm ext}}
(I_1V_1\oplus I_0V_2\oplus I_2)
=\{{D>B_1,\ B_1>D\}}.
$$

No row has external support $(\widetilde\phi_2,\widetilde\phi_3)$ or
$(\widetilde\phi_3,\widetilde\phi_2)$.  Removing an internal edge by a
Schwinger cut preserves external ports, hence

$$
\Delta_{{\rm vector\ bridge}}(C_2>C_3)
=\Delta_{{\rm vector\ bridge}}(C_3>C_2)=0.
$$

Consequently the vector-frame orbit cannot equal

$$
(-1,0,+i\sqrt2,-i\sqrt2).
$$

## 3. Exact similarity chain

For the matter endpoint/link/seagull chain,

$$
e^{{V/2}}e^{{-V}}e^{{V/2}}=1.
$$

At order $V^2$ the six terms are

$$
\frac18+\frac12+\frac18-\frac12+\frac14-\frac12=0.
$$

The $I_2$ one-propagator self-contractions have no injected loop momentum and
are massless scaleless tadpoles, hence their dimensional-regularization value
is exactly zero.

## 4. Claim boundary

Before any Ward comparison, both graph families must be moved to the same
total-derivative quotient.  For $G_1$,

$$
(2,2)_{{(\mathrm{{pair}},\mathrm{{EOM}})}}
\xrightarrow{{\ T_{{DB}}=\mathrm{{pair}}+\mathrm{{EOM}}\ }}
(0,2)_{{(\mathrm{{pair}},T_{{DB}})}}.
$$

For $G_2$,

$$
\left(-\frac13,\frac43\right)_{{(\mathrm{{pair}},\mathrm{{EOM}})}}
\xrightarrow{{\ T_{{BD}}=-\mathrm{{pair}}+\mathrm{{EOM}}\ }}
\left(1,\frac43\right)_{{(\mathrm{{pair}},T_{{BD}})}}.
$$

Hence the common compact TD vector is

$$
v_{{\rm TD}}=(0,1,-2i\sqrt2,+2i\sqrt2).
$$

The former hybrid vector used the first coordinate before the $G_1$ TD map:

$$
\pi_{{\rm EOM}}^{{G_1}}(2,2)=2
\ne
\pi_{{\rm TD}}^{{G_1}}(2,2)=0.
$$

This is its first false equality.

With

$$
M_q=
\begin{{pmatrix}}
1&-1&0&0\\
i\sqrt2&0&1&0\\
-i\sqrt2&0&0&1
\end{{pmatrix}},
$$

the topology support theorem imposes

$$
\delta v_{{\rm graph}}=(\delta_{{DB}},\delta_{{BD}},0,0).
$$

If this missing-graph support alone were required to solve the Ward equation,
then

$$
M_q(v_{{\rm TD}}+\delta v_{{\rm graph}})=0
$$

would have the unique hypothetical solution

$$
\delta v_{{\rm graph}}^{{\rm hyp}}=(2,1,0,0),
$$

and therefore

$$
v_{{\rm TD}}+\delta v_{{\rm graph}}^{{\rm hyp}}
=2k_q,
\qquad
k_q=(1,1,-i\sqrt2,+i\sqrt2).
$$

This scale-two ray conflicts with the target-blind Project $AA$ coefficient,
whose common supermultiplet scale is one.  Hence

$$
\delta v_{{\rm graph}}^{{\rm hyp}}=(2,1,0,0)
$$

is not the final completion.

## 5. General finite composite-source settlement

A general finite composite-source counterterm is not restricted by the
external support of missing Feynman graphs.  The three exact conditions are

$$
M_qv_{{\rm ren}}=0,
\qquad
q_1Y_1=iZ,
\qquad
t_{{AA}}=1.
$$

Thus $v_{{\rm ren}}=k_q$ and

$$
\boxed{{
\delta v_{{\rm fin}}
=v_{{\rm ren}}-v_{{\rm TD}}
=(1,0,+i\sqrt2,-i\sqrt2).}}
$$

Equivalently,

$$
\boxed{{
\delta\Gamma_{{\rm fin}}^{{AB}}
=\lambda_1\mathbb F^{{AB}}{{}}_{{DE}}
\left[
\langle D^D,B_1^E\rangle
+i\sqrt2\langle C_2^D,C_3^E\rangle
-i\sqrt2\langle C_3^D,C_2^E\rangle
\right].}}
$$

The completed vector is exactly

$$
\boxed{{
v_{{\rm ren}}
=v_{{\rm TD}}+\delta v_{{\rm fin}}
=(1,1,-i\sqrt2,+i\sqrt2)
=k_q,}}
\qquad
M_qv_{{\rm ren}}=0.
$$

## 6. Claim boundary

The graph-support theorem proves $\delta_{{CC}}^{{\rm graph}}=0$ for the
vector-frame orbit.  It neither derives nor constrains the $CC$ entries of a
general finite composite-source counterterm.  No $Q_0$-exact preimage is
claimed by this component linear-system audit.
"""


def canonical_bytes(value: object) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    artifact = build_artifact()
    json_bytes = canonical_bytes(artifact)
    md_bytes = markdown(artifact).encode("utf-8")
    if args.check:
        if JSON_OUT.read_bytes() != json_bytes:
            raise SystemExit(f"stale artifact: {JSON_OUT}")
        if MD_OUT.read_bytes() != md_bytes:
            raise SystemExit(f"stale artifact: {MD_OUT}")
    else:
        JSON_OUT.write_bytes(json_bytes)
        MD_OUT.write_bytes(md_bytes)
    print(json.dumps(artifact["checks"], indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
