#!/usr/bin/env python3
"""Physical WW triangle/cut/contact/link pole audit.

Inputs are the CURRENT locked foundations plus the local ordered-source
proposal generated by step5_ww_contact_link_completion_audit.py.  The HT
target and all other untracked Step-5 artifacts are deliberately excluded.

The equality of pole magnitudes is derived from:
  (i) occurrence-resolved D-algebra signs,
  (ii) exact Gaussian coefficient integration by parts (3D.34), and
  (iii) independent triangle and bubble Laurent residues.
It is not installed as a definition.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from fractions import Fraction
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
AUTHORITY_COMMIT = "00000f748fe4bdd1b5d122663cc1fb814faace66"
VERIFY_RUN = "29306335742"
SOURCE_PROPOSAL = "audits/step5-ww-contact-link-completion.json"
SOURCE_PROPOSAL_SHA256 = (
    "322a92140e557fee666df4bfb652dfb6472aa07a915fa1ea8a8501e5d18635cd"
)

FOUNDATIONS = (
    (
        "contracts/foundations/step-01-supersymmetry-commutator.md",
        "a73d8017c2d07de578f4f98ea25054033b0384ebffb6b426650a22f404c3231b",
        "Euclidean sigma identities",
    ),
    (
        "contracts/foundations/step-02a-flat-superspace.md",
        "6694f46634d604fac6a8866323c7325a803cbf3079a5771ddea25772c91cef2d",
        "(2A.41)--(2A.43): Euclidean D algebra",
    ),
    (
        "contracts/foundations/step-03a-gauge-chiral-action.md",
        "48141fc931580f6b73e385b8f900b3e6df5939cdb9348042de07fd8fe9320967",
        "(3A.34), (3A.48), (3A.51): connection and W",
    ),
    (
        "contracts/foundations/step-03c-gauge-vector-representation.md",
        "c4cc6f0504b79e02ce78030ad79b625bee6da7dff9de0f6a1ddc3b33ef2584a1",
        "(3C.18), (3C.33)--(3C.45): covariance and curvature",
    ),
    (
        "contracts/foundations/step-03d-n1-superfield-path-integral-bv-brst.md",
        "109e0c531da3a1b98313e87dd692fa3d9047c8f745291f8e87021008c7acc538",
        "(3D.34), (3D.80)--(3D.93): Schwinger equation and gauge family",
    ),
    (
        "contracts/foundations/step-04c-n4-super-yang-mills.md",
        "fafc3bc2227b60ca699b3f953b632db82dafe093b221baa74736cc5fb838928f",
        "(4C.1), (4C.4): canonical coupling normalization",
    ),
)

ORIENTATIONS = ("A_to_Wtilde__B_to_W", "B_to_Wtilde__A_to_W")
PLACEMENTS = ("Dminus_left", "Dminus_right")
TRIANGLE_ENDPOINTS = (
    ("r0", "r1", -1, -1),
    ("r0", "r2", +1, +1),
    ("r1", "r1", +1, +1),
    ("r1", "r2", -1, -1),
)
CONTACT_ENDPOINTS = (
    ("D_A barD_C", +1, -1),
    ("D_A (-barD_A)", -1, +1),
    ("(-D_C) barD_C", -1, +1),
    ("(-D_C)(-barD_A)", +1, -1),
)


def q(value: Fraction) -> dict[str, int]:
    return {"numerator": value.numerator, "denominator": value.denominator}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def input_checks() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    rows: list[dict[str, Any]] = []
    checks: list[dict[str, Any]] = []
    for rel, expected, use in FOUNDATIONS:
        actual = sha256(ROOT / rel)
        status = "PASS" if actual == expected else "FAIL"
        rows.append(
            {
                "path": rel,
                "sha256": actual,
                "expected_sha256": expected,
                "use": use,
                "status": status,
            }
        )
        checks.append({"id": f"input_hash::{rel}", "status": status})
    proposal_actual = sha256(ROOT / SOURCE_PROPOSAL)
    proposal_status = (
        "PASS" if proposal_actual == SOURCE_PROPOSAL_SHA256 else "FAIL"
    )
    rows.append(
        {
            "path": SOURCE_PROPOSAL,
            "sha256": proposal_actual,
            "expected_sha256": SOURCE_PROPOSAL_SHA256,
            "use": "ordered source, Duhamel expansion, and occurrence labels",
            "status": proposal_status,
        }
    )
    checks.append(
        {"id": "input_hash::ordered_source_proposal", "status": proposal_status}
    )
    return rows, checks


def new_step5_definitions() -> list[dict[str, str]]:
    return [
        {
            "id": "DEF-WW-PHYS-01",
            "definition": (
                "Stay in the vector-frame residual-free canonical coordinate v "
                "and choose the background supersymmetric Fermi-Feynman slice "
                "with S0=(1/2) int v^A kappa_AB(-partial^2)v^B."
            ),
            "consequence": (
                "G^{AB}(p;theta1,theta2)=hbar*kappa^{AB}"
                "*delta^4(theta1-theta2)/p^2 and K*G=hbar*identity."
            ),
        },
        {
            "id": "DEF-WW-PHYS-02",
            "definition": (
                "Choose a constant coefficient density in this residual-free "
                "canonical chart. Measure divergence in (3D.34) is zero."
            ),
            "consequence": (
                "The coefficient Schwinger identity contains only insertion "
                "derivatives and the Euler insertion."
            ),
        },
        {
            "id": "DEF-WW-PHYS-03",
            "definition": (
                "DRED: d=4-2*epsilon, delta4=hatdelta+brevedelta, "
                "tr(hatdelta)=d, tr(brevedelta)=2*epsilon; loop momenta are "
                "hatted and external p,q,w have no breve components."
            ),
            "consequence": (
                "Loop tensor reduction returns hatdelta; four-dimensional "
                "D-algebra returns delta4."
            ),
        },
        {
            "id": "DEF-WW-PHYS-04",
            "definition": (
                "Fourier phase exp(+i p.x), mathsf p_a dot-a="
                "-i sigma^m_a dot-a p_m, so {D_a,barD_dot-a}=2 mathsf p_a dot-a."
            ),
            "consequence": "The i from the barW vertex and -i from mathsf p multiply to +1.",
        },
        {
            "id": "DEF-WW-PHYS-05",
            "definition": (
                "Use exactly S_J=int J_AB L^A(tau_w L)^B from the source "
                "proposal. No independent curvature improvement or local J counterterm "
                "is included in the bare insertion."
            ),
            "consequence": (
                "Every order-g^2 source vertex is generated by L1,L2,L3 and "
                "T0,T1,T2; no coefficient is adjusted to enforce a pole match."
            ),
        },
        {
            "id": "DEF-WW-PHYS-06",
            "definition": (
                "Retain occurrence tags through all superspace integrations by parts. "
                "A cut row is the full product-rule descendant of one tagged parent row."
            ),
            "consequence": (
                "Topology reallocations may change nonlinear/quartic/collapsed labels, "
                "but cannot change an occurrence-row sum."
            ),
        },
    ]


def gaussian_cut_identity() -> dict[str, Any]:
    return {
        "euclidean_coefficient_identity": [
            "0=int Dv delta/dv^I [F^I(v) exp(-S0/hbar)]",
            (
                "0=<delta F^I/dv^I>-(1/hbar)"
                "<F^I delta S0/dv^I>"
            ),
            (
                "<F^I K_IJ v^J>-hbar<delta F^I/dv^I>=0"
            ),
        ],
        "ward_combination": (
            "parent inverse-kernel occurrence minus its product-rule "
            "functional derivative"
        ),
        "relative_cut_sign": -1,
        "why_not_a_definition": (
            "The sign is the minus sign between the two terms obtained by "
            "differentiating exp(-S0/hbar); no contact coefficient is inserted."
        ),
        "product_rule_exhaustion": [
            {
                "derivative_target": "L1/L2/L3 in the insertion",
                "sector": "NONLINEAR_LETTER",
            },
            {
                "derivative_target": "cubic action word",
                "sector": "QUARTIC_ACTION",
            },
            {
                "derivative_target": "edge projector/inverse kernel",
                "sector": "COLLAPSED_DALGEBRA",
            },
            {
                "derivative_target": "T1",
                "sector": "ONE_LINK",
            },
            {
                "derivative_target": "T2 or the second link derivative",
                "sector": "TWO_LINK",
            },
            {
                "derivative_target": "left/right transported endpoint",
                "sector": "EXTERNAL_ENDPOINT",
            },
            {
                "derivative_target": "constant coefficient density",
                "sector": "ZERO_BY_DEF_WW_PHYS_02",
            },
            {
                "derivative_target": "FP/NK field",
                "sector": "ABSENT_NO_GHOST_PORT_IN_S_J",
            },
        ],
    }


def triangle_dalgebra() -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    for index, (bar_edge, d_edge, raw, transfer) in enumerate(
        TRIANGLE_ENDPOINTS, start=1
    ):
        rows.append(
            {
                "id": f"T-DA-{index:02d}",
                "barD_edge": bar_edge,
                "D_edge": d_edge,
                "raw_vertex_sign": raw,
                "endpoint_transfer_sign": transfer,
                "final_sign": raw * transfer,
                "uv_numerator": "ell^mu p^rho ell^nu",
                "rank_two_residue_in_B0_units": q(Fraction(1, 4)),
            }
        )
    vertex_product = Fraction(1, 4)
    insertion_closed_loop_weight = Fraction(2)
    common = vertex_product * insertion_closed_loop_weight
    b0_residue = Fraction(1, 16)
    rank_two = Fraction(1, 4)
    row_pole = common * rank_two * b0_residue
    total_pole = len(rows) * row_pole
    return {
        "rows": rows,
        "factor_chain": {
            "fixed_orientation_action_order_weight": q(Fraction(1)),
            "vertex_product_without_g2": q(vertex_product),
            "insertion_KK_Dminus_coefficient": q(Fraction(1, 32)),
            "closed_D_loop": q(Fraction(16)),
            "two_mixed_anticommutators": [q(Fraction(2)), q(Fraction(2))],
            "insertion_and_closed_D_loop": q(insertion_closed_loop_weight),
            "common_prefactor_without_hbar_g2": q(common),
            "single_row_rank_two_in_B0_units": q(rank_two),
            "B0_residue_without_pi2": q(b0_residue),
        },
        "single_row_pole_without_hbar_g2_pi2": q(row_pole),
        "four_row_pole_without_hbar_g2_pi2": q(total_pole),
        "pole": (
            "+hbar*g^2/(32*pi^2*epsilon) color*word*"
            "T_mu rho nu*hatdelta^mu nu"
        ),
    }


def contact_dalgebra() -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    kplus = Fraction(-1, 4)
    dminus_dplus = Fraction(1, 2)
    mixed = Fraction(2)
    wick_pairings = Fraction(2)
    tensor_conversion = Fraction(-1, 2)
    for index, (word, raw, transfer) in enumerate(CONTACT_ENDPOINTS, start=1):
        effective = raw * transfer
        multiplier = (
            kplus
            * effective
            * dminus_dplus
            * mixed
            * wick_pairings
            * tensor_conversion
        )
        rows.append(
            {
                "id": f"C-DA-{index:02d}",
                "raw_word": word,
                "raw_difference_sign": raw,
                "endpoint_transfer_sign": transfer,
                "effective_sign_before_Kplus": effective,
                "factor_trace": [
                    ["K_plus", q(kplus)],
                    ["effective_endpoint_sign", q(Fraction(effective))],
                    ["D_minus_D_plus_to_half_D2", q(dminus_dplus)],
                    ["mixed_anticommutator", q(mixed)],
                    ["ordered_two_line_Wick_pairings", q(wick_pairings)],
                    ["p_plus_to_delta4_Tp", q(tensor_conversion)],
                ],
                "metric_multiplier_in_B0_units": q(multiplier),
            }
        )
    common = Fraction(1, 2)
    b0_residue = Fraction(1, 16)
    row_metric = Fraction(
        rows[0]["metric_multiplier_in_B0_units"]["numerator"],
        rows[0]["metric_multiplier_in_B0_units"]["denominator"],
    )
    row_pole = common * row_metric * b0_residue
    total_pole = len(rows) * row_pole
    return {
        "aggregate_derivative_word": (
            "(D_minus^A-D_minus^C) K_plus "
            "(barD^C-barD^A)"
        ),
        "aggregate_source_word": (
            "g*c^{BCE}*X^E*[(D_minus K_plus v^A)v^C"
            "-(K_plus v^A)D_minus v^C] modulo EOM"
        ),
        "aggregate_source_origin": (
            "sum of the product-rule descendants listed in gaussian_cut_identity; "
            "it is not an added bare vertex"
        ),
        "rows": rows,
        "common_prefactor": [
            "source order g",
            "barW vertex +i*g/2",
            "mathsf p Fourier phase -i",
            "(+i)*(-i)=+1",
            "therefore +g^2/2 before the row multiplier",
            "the ordered two-line Wick factor 2 is retained inside each row multiplier",
        ],
        "common_prefactor_without_hbar_g2": q(common),
        "B0_residue_without_pi2": q(b0_residue),
        "single_row_pole_without_hbar_g2_pi2": q(row_pole),
        "four_row_pole_without_hbar_g2_pi2": q(total_pole),
        "pole": (
            "-hbar*g^2/(32*pi^2*epsilon) color*word*"
            "T_mu rho nu*delta4^mu nu"
        ),
    }


def physical_orbits(
    triangle: dict[str, Any], contact: dict[str, Any]
) -> list[dict[str, Any]]:
    t_rows = triangle["rows"]
    c_rows = contact["rows"]
    out: list[dict[str, Any]] = []
    for orientation in ORIENTATIONS:
        for placement in PLACEMENTS:
            cut_edge = "r0" if placement == "Dminus_left" else "r2"
            for index, (trow, crow) in enumerate(zip(t_rows, c_rows), start=1):
                out.append(
                    {
                        "id": f"{orientation}::{placement}::occurrence-{index}",
                        "orientation": orientation,
                        "marked_Dminus_placement": placement,
                        "marked_cut_edge": cut_edge,
                        "barD_edge": trow["barD_edge"],
                        "D_edge": trow["D_edge"],
                        "triangle_final_sign": trow["final_sign"],
                        "contact_effective_sign": crow[
                            "effective_sign_before_Kplus"
                        ],
                        "triangle_pole": (
                            "+hbar*g^2/(128*pi^2*epsilon)*hatdelta"
                        ),
                        "contact_pole": (
                            "-hbar*g^2/(128*pi^2*epsilon)*delta4"
                        ),
                        "same_color_word": True,
                        "same_external_word": True,
                        "reflected_or_other_placement_is_not_multiplicity": True,
                    }
                )
    return out


def link_poles(row_magnitude: Fraction) -> dict[str, Any]:
    return {
        "row_magnitude_without_hbar_g2_pi2": q(row_magnitude),
        "one_link_rows": [
            {
                "triangle_longitudinal": "+C_row*(E(r)-E(r'))",
                "one_link": (
                    "-C_row*i*w.(r-r')*int_0^1 ds "
                    "exp(i*s*w.r)exp(i*(1-s)*w.r')"
                ),
                "identity": (
                    "i*w.(r-r')*int_0^1 ds ...=E(r)-E(r')"
                ),
                "sum": "0",
            }
        ],
        "two_link_rows": [
            {
                "bulk": (
                    "i*w.(r0-r1)*int_{0<=a<=b<=1}E012"
                ),
                "boundary": "int_0^1 db [E02(b)-E12(b)]",
                "one_link_completion": "negative of the boundary",
                "sum": "0",
            },
            {
                "bulk": (
                    "i*w.(r1-r2)*int_{0<=a<=b<=1}E012"
                ),
                "boundary": "int_0^1 da [E01(a)-E02(a)]",
                "one_link_completion": "negative of the boundary",
                "sum": "0",
            },
        ],
        "endpoint": {
            "link_right_endpoint_coefficient": -1,
            "transported_field_coefficient": +1,
            "sum": 0,
        },
        "total_longitudinal_pole": "0",
    }


def checks(
    inputs: list[dict[str, Any]],
    triangle: dict[str, Any],
    contact: dict[str, Any],
    orbits: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = [
        {"id": row["id"], "status": row["status"]}
        for row in inputs
    ]
    trow = Fraction(
        triangle["single_row_pole_without_hbar_g2_pi2"]["numerator"],
        triangle["single_row_pole_without_hbar_g2_pi2"]["denominator"],
    )
    crow = Fraction(
        contact["single_row_pole_without_hbar_g2_pi2"]["numerator"],
        contact["single_row_pole_without_hbar_g2_pi2"]["denominator"],
    )
    ttotal = Fraction(
        triangle["four_row_pole_without_hbar_g2_pi2"]["numerator"],
        triangle["four_row_pole_without_hbar_g2_pi2"]["denominator"],
    )
    ctotal = Fraction(
        contact["four_row_pole_without_hbar_g2_pi2"]["numerator"],
        contact["four_row_pole_without_hbar_g2_pi2"]["denominator"],
    )
    result.extend(
        [
            {
                "id": "triangle_endpoint_signs_all_plus",
                "status": (
                    "PASS"
                    if all(row["final_sign"] == 1 for row in triangle["rows"])
                    else "FAIL"
                ),
            },
            {
                "id": "contact_endpoint_effective_signs_all_minus",
                "status": (
                    "PASS"
                    if all(
                        row["effective_sign_before_Kplus"] == -1
                        for row in contact["rows"]
                    )
                    else "FAIL"
                ),
            },
            {
                "id": "contact_row_Dalgebra_multiplier_minus_quarter",
                "status": (
                    "PASS"
                    if all(
                        row["metric_multiplier_in_B0_units"]
                        == q(Fraction(-1, 4))
                        for row in contact["rows"]
                    )
                    else "FAIL"
                ),
            },
            {
                "id": "single_triangle_row_is_plus_1_over_128",
                "status": "PASS" if trow == Fraction(1, 128) else "FAIL",
            },
            {
                "id": "single_contact_row_is_minus_1_over_128",
                "status": "PASS" if crow == Fraction(-1, 128) else "FAIL",
            },
            {
                "id": "aggregate_triangle_is_plus_1_over_32",
                "status": "PASS" if ttotal == Fraction(1, 32) else "FAIL",
            },
            {
                "id": "aggregate_contact_is_minus_1_over_32",
                "status": "PASS" if ctotal == Fraction(-1, 32) else "FAIL",
            },
            {
                "id": "pole_magnitudes_C_C_equals_C_T",
                "status": "PASS" if -ctotal == ttotal else "FAIL",
            },
            {
                "id": "sixteen_already_oriented_occurrence_orbits",
                "status": "PASS" if len(orbits) == 16 else "FAIL",
            },
            {
                "id": "no_orientation_or_placement_double_count",
                "status": (
                    "PASS"
                    if all(
                        row["reflected_or_other_placement_is_not_multiplicity"]
                        for row in orbits
                    )
                    else "FAIL"
                ),
            },
        ]
    )
    return result


def build() -> dict[str, Any]:
    input_rows, input_check_rows = input_checks()
    triangle = triangle_dalgebra()
    contact = contact_dalgebra()
    orbits = physical_orbits(triangle, contact)
    trow = Fraction(
        triangle["single_row_pole_without_hbar_g2_pi2"]["numerator"],
        triangle["single_row_pole_without_hbar_g2_pi2"]["denominator"],
    )
    all_checks = checks(input_check_rows, triangle, contact, orbits)
    return {
        "schema": "awi.step5.ww-physical-cut-pole-audit.v1",
        "authority_commit": AUTHORITY_COMMIT,
        "verify_run": VERIFY_RUN,
        "input_boundary": {
            "read": [item[0] for item in FOUNDATIONS] + [SOURCE_PROPOSAL],
            "not_read": [
                "HT target",
                "untracked canonical seed audit",
                "untracked Step-5 contract",
                "other untracked Step-5 engines/audits",
                "live chats",
                "Notion",
            ],
        },
        "inputs": input_rows,
        "new_step5_definitions": new_step5_definitions(),
        "gaussian_cut_identity": gaussian_cut_identity(),
        "triangle_Dalgebra_and_residue": triangle,
        "contact_Dalgebra_and_residue": contact,
        "occurrence_orbits": orbits,
        "link_and_endpoint_poles": link_poles(trow),
        "result": {
            "definition_of_C_T_and_C_C": (
                "Gamma_T=(C_T/epsilon)*hatdelta; "
                "Gamma_C=-(C_C/epsilon)*delta4"
            ),
            "C_T": (
                "hbar*g^2/(32*pi^2) times the fixed color/external/ordered kernel"
            ),
            "C_C": (
                "hbar*g^2/(32*pi^2) times the same fixed color/external/ordered kernel"
            ),
            "magnitude_equality": "C_C=C_T",
            "derivation_not_definition": True,
            "metric_sum": (
                "-hbar*g^2/(32*pi^2*epsilon)*"
                "color*ordered_kernel*T_mu rho nu*brevedelta^mu nu"
            ),
            "breve_contraction": (
                "brevedelta^mu nu*T_mu rho nu*p^rho="
                "-2*epsilon*sigma_rho*p^rho"
            ),
            "finite_defect": (
                "+hbar*g^2/(16*pi^2)*"
                "color*ordered_kernel*barW_dot-alpha*p_+^dot-alpha*X"
            ),
            "longitudinal_pole_after_link_completion": "0",
        },
        "checks": all_checks,
        "exact_blockers": [
            {
                "id": "BLOCKED_EXPLICIT_WW_D_ALGEBRA_WORD_DERIVATION",
                "claim": "the recorded endpoint-transfer signs and mixed-anticommutator factors are derived from a complete superspace D-word trace",
                "reason": (
                    "The present audit checks coefficient arithmetic after those signs "
                    "and factors are supplied. It does not emit the noncommutative "
                    "integration-by-parts rewrite chain."
                ),
                "does_not_block": "conditional arithmetic consistency of the displayed FF pole ledger",
            },
            {
                "id": "BLOCKED_TOPOLOGY_RESOLVED_CONTACT_ALLOCATION",
                "claim": (
                    "A unique separate pole for NONLINEAR_LETTER, "
                    "QUARTIC_ACTION, COLLAPSED_R0/R1/R2, ONE_LINK, and TWO_LINK."
                ),
                "reason": (
                    "Superspace integration by parts and ordered vertex "
                    "symmetrization move terms among these topology names while "
                    "preserving each occurrence-row sum. CURRENT has no locked "
                    "D-algebra normal form selecting one allocation."
                ),
                "does_not_block": "aggregate C_C=C_T",
            },
            {
                "id": "BLOCKED_RENORMALIZED_COMPOSITE_MIXING",
                "claim": "renormalized contact-sector closure",
                "reason": (
                    "The local composite basis and evanescent-to-physical "
                    "one-loop mixing matrix are not locked."
                ),
                "does_not_block": "bare one-loop aggregate metric mismatch",
            },
            {
                "id": "PROPOSAL_NOT_AUTHORITY",
                "claim": "use of DEF-WW-PHYS-01--06 as Project law",
                "reason": (
                    "The definitions and this derivation are uncommitted proposals "
                    "until reviewed origin/main passes verify."
                ),
                "does_not_block": "internal reproducibility of this audit",
            },
        ],
        "overall_status": (
            "CONDITIONAL_FF_AGGREGATE_BARE_POLE_ARITHMETIC_CHECKED__"
            "BLOCKED_D_WORD_TOPOLOGY_ALLOCATION_AND_RENORMALIZED_MIXING"
        ),
    }


def markdown(audit: dict[str, Any]) -> str:
    input_table = "\n".join(
        f"| {row['path']} | {row['sha256']} | {row['status']} |"
        for row in audit["inputs"]
    )
    definition_table = "\n".join(
        f"| {row['id']} | {row['definition']} | {row['consequence']} |"
        for row in audit["new_step5_definitions"]
    )
    triangle_rows = "\n".join(
        (
            f"| {row['id']} | {row['barD_edge']} | {row['D_edge']} | "
            f"{row['raw_vertex_sign']} | {row['endpoint_transfer_sign']} | "
            f"{row['final_sign']} | $+1/128$ |"
        )
        for row in audit["triangle_Dalgebra_and_residue"]["rows"]
    )
    contact_rows = "\n".join(
        (
            f"| {row['id']} | {row['raw_word']} | "
            f"{row['raw_difference_sign']} | {row['endpoint_transfer_sign']} | "
            f"{row['effective_sign_before_Kplus']} | $-1/4$ | $-1/128$ |"
        )
        for row in audit["contact_Dalgebra_and_residue"]["rows"]
    )
    checks_table = "\n".join(
        f"| {row['id']} | {row['status']} |" for row in audit["checks"]
    )
    blocker_table = "\n".join(
        f"| {row['id']} | {row['claim']} | {row['reason']} |"
        for row in audit["exact_blockers"]
    )
    template = r"""# Step 5 WW physical cut/contact/link pole audit

Authority base: __AUTHORITY__; verify run __VERIFY__.
HT target 与其他 untracked Step-5 calculations 未进入系数推导。

## 1. Inputs

| input | SHA-256 | check |
|---|---|---|
__INPUT_TABLE__

## 2. Minimal new Step-5 definitions

| id | definition | consequence |
|---|---|---|
__DEFINITION_TABLE__

这些 definitions 固定 gauge/source/regulator；没有把 $C_C=C_T$ 写成 definition。

## 3. Schwinger cut sign

在 DEF-WW-PHYS-02 的 canonical coefficient measure 中，

$$
0=\int Dv\,
\frac{\delta}{\delta v^I}
\left[F^I(v)e^{-S_0/\hbar}\right],
$$

$$
0=
\left\langle\frac{\delta F^I}{\delta v^I}\right\rangle
-\frac1\hbar
\left\langle F^I\frac{\delta S_0}{\delta v^I}\right\rangle.
$$

因此 Ward combination 为

$$
\left\langle F^IK_{IJ}v^J\right\rangle
-\hbar\left\langle\frac{\delta F^I}{\delta v^I}\right\rangle=0.
$$

故 occurrence-decorated cut/contact 相对 parent 的 sign 是 $-1$。这是
$e^{-S_0/\hbar}$ 的 functional derivative sign，不是 coefficient definition。

对 order $g^2$ source/action，functional derivative 只能落在

$$
\{L_1,L_2,L_3;\ S_3;\ K_e;\ T_1,T_2;\
\text{left endpoint},\text{right endpoint},\varpi\}.
$$

它们分别产生 nonlinear-letter、quartic、collapsed、one-link、two-link、
endpoint 与 measure rows；constant $\varpi$ row 为零。$S_J$ 没有 ghost port。

## 4. Four triangle endpoint rows

固定 orientation 与一个 marked $D_-$ placement：

| row | $\bar D$ edge | $D$ edge | raw | transfer | final | pole coefficient |
|---|---:|---:|---:|---:|---:|---:|
__TRIANGLE_ROWS__

每行 UV-leading numerator 是

$$
\ell^\mu p^\rho\ell^\nu.
$$

固定 orientation 的 interaction/Wick/$D$-algebra coefficient 为

$$
\left(\frac14\right)_{\widetilde W,W\ {\rm vertices}}
\left(\frac1{32}\right)_{D_-K_+K_+}
(16)_{\rm closed\ D-loop}
(2)(2)_{\rm mixed}
=\frac12.
$$

这里

$$
\frac1{2!}(S_{\widetilde W}S_W+S_WS_{\widetilde W})=1
$$

已经包含在 fixed-orientation weight；不再乘 reflection。

Feynman parametrization 给出

$$
\frac1{D_0D_1D_2}
=2\int_{\Delta_2}\frac1{(\ell^2+\Delta)^3},
\qquad
\int_{\Delta_2}1=\frac12,
$$

$$
\int_\ell
\frac{\ell^\mu\ell^\nu}{(\ell^2+\Delta)^3}
\bigg|_{\rm pole}
=\frac14\widehat\delta^{\mu\nu}
\frac1{16\pi^2\epsilon}.
$$

故 single row residue 是

$$
\frac{\hbar g^2}{2}
\times\frac14
\times\frac1{16\pi^2\epsilon}
=\frac{\hbar g^2}{128\pi^2\epsilon}.
$$

四行严格相加：

$$
\boxed{
\Gamma_{T,\rm pole}^{A|B}
=+\frac{\hbar g^2}{32\pi^2\epsilon}
\mathcal C^{AB}{}_{DE}\,
\mathcal K_w[\widetilde W^D_{\dot\alpha},p^\rho X^E]\,
T_{\mu\rho\nu,+}{}^{\dot\alpha}
\widehat\delta^{\mu\nu}}.
$$

## 5. Four cut/contact D-algebra rows

Aggregate derivative-difference word 是

$$
(D_-^A-D_-^C)K_+
(\bar D^C-\bar D^A).
$$

它来自 Section 3 的完整 product-rule descendant sum；不是新增 bare
contact vertex。逐项展开：

| row | raw word | raw | transfer | effective before $K_+$ | metric/B0 | pole |
|---|---|---:|---:|---:|---:|---:|
__CONTACT_ROWS__

每行的 exact factor chain：

contact source 与 $\widetilde W$ vertex 的 common coefficient 是

$$
(g)\left(\frac{ig}{2}\right)(-i)_{\mathsf p}
=\frac{g^2}{2}.
$$

两个 ordered quantum-line pairings 保留在 row factor 中。故

$$
\left(-\frac14\right)_{K_+}
(-1)_{\rm endpoint}
\left(\frac12\right)_{D_-D_+=D^2/2}
(2)_{\{D_+,\bar D\}}
(2)_{\rm Wick}
\left(-\frac12\right)_{p_+=-\delta_4Tp/2}
=-\frac14.
$$

这里乘法是普通乘法：

$$
\left(-\frac14\right)(-1)
\left(\frac12\right)(2)(2)
\left(-\frac12\right)
=-\frac14.
$$

Bubble pole：

$$
B_0(Q^2)
=\mu^{2\epsilon}\int\frac{d^dk}{(2\pi)^d}
\frac1{k^2(k+Q)^2},
$$

$$
B_0(Q^2)\big|_{\rm pole}
=\frac1{16\pi^2\epsilon}.
$$

single cut row 因而为

$$
\frac{\hbar g^2}{2}
\left(-\frac14\right)
\frac1{16\pi^2\epsilon}
=-\frac{\hbar g^2}{128\pi^2\epsilon}.
$$

四行相加：

$$
\boxed{
\Gamma_{C,\rm pole}^{A|B}
=-\frac{\hbar g^2}{32\pi^2\epsilon}
\mathcal C^{AB}{}_{DE}\,
\mathcal K_w[\widetilde W^D_{\dot\alpha},p^\rho X^E]\,
T_{\mu\rho\nu,+}{}^{\dot\alpha}
\delta_4^{\mu\nu}}.
$$

定义 positive magnitudes

$$
\Gamma_T=\frac{C_T}{\epsilon}\widehat\delta,\qquad
\Gamma_C=-\frac{C_C}{\epsilon}\delta_4.
$$

上面两个 independent residue calculations 给出

$$
\boxed{C_C=C_T=
\frac{\hbar g^2}{32\pi^2}
\mathcal C^{AB}{}_{DE}\mathcal K_w[\widetilde W^D,pX]T}.
$$

## 6. Link and endpoint pole

每个 occurrence 的 longitudinal residue 写成

$$
C_{\rm row}\left[e^{iw\cdot r}-e^{iw\cdot r'}\right].
$$

one-link graph 给出

$$
-C_{\rm row}\,iw\cdot(r-r')
\int_0^1ds\,
e^{isw\cdot r}e^{i(1-s)w\cdot r'}.
$$

由 Duhamel identity，两式和严格为 $0$。

two-link bulk 的两个 exact boundary reductions：

$$
iw\cdot(r_0-r_1)\int_{0\le a\le b\le1}E_{012}
=\int_0^1db\,[E_{02}(b)-E_{12}(b)],
$$

$$
iw\cdot(r_1-r_2)\int_{0\le a\le b\le1}E_{012}
=\int_0^1da\,[E_{01}(a)-E_{02}(a)].
$$

它们分别被 one-link rows 抵消；right endpoint coefficient 为

$$
-1+1=0.
$$

所以

$$
\boxed{\Gamma_{\rm longitudinal,pole}^{A|B}=0}.
$$

## 7. Metric mismatch

$$
\delta_4^{\mu\nu}
=\widehat\delta^{\mu\nu}+\breve\delta^{\mu\nu}.
$$

因此

$$
\boxed{
\Gamma_{T+C,\rm pole}^{A|B}
=-\frac{\hbar g^2}{32\pi^2\epsilon}
\mathcal C^{AB}{}_{DE}\,
\mathcal K_w[\widetilde W^D_{\dot\alpha},p^\rho X^E]\,
T_{\mu\rho\nu,+}{}^{\dot\alpha}
\breve\delta^{\mu\nu}}.
$$

$$
\breve\delta^{\mu\nu}
T_{\mu\rho\nu,+}{}^{\dot\alpha}p^\rho
=-2\epsilon\,p_+{}^{\dot\alpha}.
$$

故 bare finite cutting defect 为

$$
\boxed{
\Gamma_{\rm defect}^{A|B}
=+\frac{\hbar g^2}{16\pi^2}
\mathcal C^{AB}{}_{DE}\,
\mathcal K_w[\widetilde W^D_{\dot\alpha},p_+{}^{\dot\alpha}X^E]}.
$$

reflected orientation 与另一个 marked $D_-$ placement 是 distinct ordered
words，不乘为额外 multiplicity。

## 8. Exact blockers

| blocker | blocked claim | reason |
|---|---|---|
__BLOCKER_TABLE__

## 9. Checks

| check | status |
|---|---|
__CHECKS_TABLE__

$$
\boxed{\text{status}=\texttt{__STATUS__}}.
$$
"""
    return (
        template.replace("__AUTHORITY__", audit["authority_commit"])
        .replace("__VERIFY__", audit["verify_run"])
        .replace("__INPUT_TABLE__", input_table)
        .replace("__DEFINITION_TABLE__", definition_table)
        .replace("__TRIANGLE_ROWS__", triangle_rows)
        .replace("__CONTACT_ROWS__", contact_rows)
        .replace("__CHECKS_TABLE__", checks_table)
        .replace("__BLOCKER_TABLE__", blocker_table)
        .replace("__STATUS__", audit["overall_status"])
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--json", default="audits/step5-ww-physical-cut-pole.json"
    )
    parser.add_argument(
        "--markdown", default="audits/step5-ww-physical-cut-pole.md"
    )
    args = parser.parse_args()
    audit = build()
    json_path = ROOT / args.json
    markdown_path = ROOT / args.markdown
    json_path.write_text(json.dumps(audit, indent=2, sort_keys=True) + "\n")
    markdown_path.write_text(markdown(audit))
    failed = [row for row in audit["checks"] if row["status"] != "PASS"]
    print(
        json.dumps(
            {
                "overall_status": audit["overall_status"],
                "failed_checks": failed,
            },
            indent=2,
        )
    )
    raise SystemExit(1 if failed else 0)


if __name__ == "__main__":
    main()
