#!/usr/bin/env python3
"""Exact Euclidean Step-2B chiral-superconformal verifier.

The coefficient field is Q(i).  Operators act on polynomials in four
commuting Euclidean chiral coordinates and the exterior algebra generated by
vartheta^1 < vartheta^2.  No floating-point arithmetic or external CAS is
used.
"""

from __future__ import annotations

from fractions import Fraction
from itertools import product
import json
from pathlib import Path


class C:
    __slots__ = ("r", "i")

    def __init__(self, r: int | Fraction = 0, i: int | Fraction = 0) -> None:
        self.r = Fraction(r)
        self.i = Fraction(i)

    def __add__(self, other: "C") -> "C":
        return C(self.r + other.r, self.i + other.i)

    def __sub__(self, other: "C") -> "C":
        return C(self.r - other.r, self.i - other.i)

    def __neg__(self) -> "C":
        return C(-self.r, -self.i)

    def __mul__(self, other: "C") -> "C":
        return C(
            self.r * other.r - self.i * other.i,
            self.r * other.i + self.i * other.r,
        )

    def __eq__(self, other: object) -> bool:
        return isinstance(other, C) and self.r == other.r and self.i == other.i

    def __repr__(self) -> str:
        return f"C({self.r},{self.i})"

    def zero(self) -> bool:
        return self.r == 0 and self.i == 0


Z = C()
O = C(1)
M = C(-1)
I = C(0, 1)
MI = C(0, -1)
TWO = C(2)
MTWO = C(-2)
HALF = C(Fraction(1, 2))

Key = tuple[int, int, int, int, int]
Poly = dict[Key, C]


def norm(p: Poly) -> Poly:
    return {key: coefficient for key, coefficient in p.items() if not coefficient.zero()}


def add(*values: Poly) -> Poly:
    out: Poly = {}
    for p in values:
        for key, coefficient in p.items():
            out[key] = out.get(key, Z) + coefficient
    return norm(out)


def scale(coefficient: C, p: Poly) -> Poly:
    return norm({key: coefficient * value for key, value in p.items()})


def basis(mask: int, exponents: tuple[int, int, int, int]) -> Poly:
    return {(mask, *exponents): O}


def mul_y(m: int, p: Poly) -> Poly:
    out: Poly = {}
    for key, coefficient in p.items():
        values = list(key)
        values[1 + m] += 1
        shifted = tuple(values)
        out[shifted] = out.get(shifted, Z) + coefficient
    return norm(out)


def dy(m: int, p: Poly) -> Poly:
    out: Poly = {}
    for key, coefficient in p.items():
        power = key[1 + m]
        if power == 0:
            continue
        values = list(key)
        values[1 + m] -= 1
        shifted = tuple(values)
        out[shifted] = out.get(shifted, Z) + C(power) * coefficient
    return norm(out)


def mul_t(a: int, p: Poly) -> Poly:
    bit = 1 << a
    out: Poly = {}
    for key, coefficient in p.items():
        mask = key[0]
        if mask & bit:
            continue
        sign = M if (mask & (bit - 1)).bit_count() % 2 else O
        shifted = (mask | bit, *key[1:])
        out[shifted] = out.get(shifted, Z) + sign * coefficient
    return norm(out)


def dt(a: int, p: Poly) -> Poly:
    bit = 1 << a
    out: Poly = {}
    for key, coefficient in p.items():
        mask = key[0]
        if not mask & bit:
            continue
        sign = M if (mask & (bit - 1)).bit_count() % 2 else O
        shifted = (mask ^ bit, *key[1:])
        out[shifted] = out.get(shifted, Z) + sign * coefficient
    return norm(out)


Matrix = tuple[tuple[C, C], tuple[C, C]]


def sum_c(values) -> C:
    out = Z
    for value in values:
        out = out + value
    return out


def mm(left: Matrix, right: Matrix) -> Matrix:
    return tuple(
        tuple(sum_c(left[row][k] * right[k][column] for k in range(2)) for column in range(2))
        for row in range(2)
    )  # type: ignore[return-value]


def msub(left: Matrix, right: Matrix) -> Matrix:
    return tuple(
        tuple(left[row][column] - right[row][column] for column in range(2))
        for row in range(2)
    )  # type: ignore[return-value]


def mscale(coefficient: C, matrix: Matrix) -> Matrix:
    return tuple(
        tuple(coefficient * matrix[row][column] for column in range(2))
        for row in range(2)
    )  # type: ignore[return-value]


SID: Matrix = ((O, Z), (Z, O))
S1: Matrix = ((Z, O), (O, Z))
S2: Matrix = ((Z, MI), (I, Z))
S3: Matrix = ((O, Z), (Z, M))

# m=0,1,2,3 denotes the Euclidean labels 1,2,3,4.
SIGE = (mscale(MI, S1), mscale(MI, S2), mscale(MI, S3), SID)
BSIGE = (mscale(I, S1), mscale(I, S2), mscale(I, S3), SID)
SIGEMN: dict[tuple[int, int], Matrix] = {}
BAREMN: dict[tuple[int, int], Matrix] = {}
for m in range(4):
    for n in range(4):
        SIGEMN[m, n] = mscale(
            C(Fraction(1, 4)),
            msub(mm(SIGE[m], BSIGE[n]), mm(SIGE[n], BSIGE[m])),
        )
        BAREMN[m, n] = mscale(
            C(Fraction(1, 4)),
            msub(mm(BSIGE[m], SIGE[n]), mm(BSIGE[n], SIGE[m])),
        )


def op_sum(*ops):
    return lambda p: add(*(operator(p) for operator in ops))


def op_scale(coefficient: C, operator):
    return lambda p: scale(coefficient, operator(p))


def comm(left, right):
    return lambda p: add(left(right(p)), scale(M, right(left(p))))


def anti(left, right):
    return lambda p: add(left(right(p)), right(left(p)))


def zero(_: Poly) -> Poly:
    return {}


def y_then_d(m: int, n: int):
    return lambda p: mul_y(m, dy(n, p))


def t_then_d(a: int, b: int):
    return lambda p: mul_t(a, dt(b, p))


def linear(terms):
    return op_sum(*(op_scale(coefficient, operator) for coefficient, operator in terms))


E = op_sum(*(y_then_d(m, m) for m in range(4)))
N = op_sum(*(t_then_d(a, a) for a in range(2)))
P = tuple(op_scale(M, lambda p, m=m: dy(m, p)) for m in range(4))
Q = tuple(op_scale(M, lambda p, a=a: dt(a, p)) for a in range(2))


def bar_q(dot: int):
    return op_sum(
        *(
            op_scale(
                MTWO * SIGE[m][a][dot],
                lambda p, a=a, m=m: mul_t(a, dy(m, p)),
            )
            for a in range(2)
            for m in range(4)
        )
    )


BQ = tuple(bar_q(dot) for dot in range(2))
DIL = op_scale(M, op_sum(E, op_scale(HALF, N)))
R = op_scale(MI, N)


def rotation(m: int, n: int):
    orbital = op_scale(MI, op_sum(y_then_d(m, n), op_scale(M, y_then_d(n, m))))
    spin = op_sum(
        *(
            op_scale(MI * SIGEMN[m, n][a][b], t_then_d(a, b))
            for a in range(2)
            for b in range(2)
        )
    )
    return op_sum(orbital, spin)


J = {(m, n): rotation(m, n) for m in range(4) for n in range(4)}


def y_squared_then_d(m: int):
    return op_sum(
        *(lambda p, r=r, m=m: mul_y(r, mul_y(r, dy(m, p))) for r in range(4))
    )


def tilde_y_entry(dot: int, a: int, p: Poly) -> Poly:
    return add(*(scale(BSIGE[n][dot][a], mul_y(n, p)) for n in range(4)))


def k_op(m: int):
    bosonic = op_sum(
        y_squared_then_d(m),
        op_scale(MTWO, lambda p, m=m: mul_y(m, E(p))),
    )
    spin = op_sum(
        *(
            op_scale(
                SIGE[m][b][dot],
                lambda p, b=b, a=a, dot=dot: mul_t(
                    b,
                    tilde_y_entry(dot, a, dt(a, p)),
                ),
            )
            for b in range(2)
            for a in range(2)
            for dot in range(2)
        )
    )
    return op_sum(op_scale(M, bosonic), spin)


K = tuple(k_op(m) for m in range(4))


def bar_s(dot: int):
    return op_sum(
        *(lambda p, dot=dot, a=a: tilde_y_entry(dot, a, dt(a, p)) for a in range(2))
    )


BS = tuple(bar_s(dot) for dot in range(2))
EPS_UP: Matrix = ((Z, O), (M, Z))


def theta_squared(p: Poly) -> Poly:
    # vartheta^a vartheta_a=-2 vartheta^1 vartheta^2.
    return scale(MTWO, mul_t(0, mul_t(1, p)))


def s_op(up: int):
    first = op_sum(
        *(
            op_scale(
                MTWO * SIGE[m][b][dot],
                lambda p, b=b, m=m, dot=dot, up=up: mul_t(
                    b,
                    tilde_y_entry(dot, up, dy(m, p)),
                ),
            )
            for b in range(2)
            for m in range(4)
            for dot in range(2)
        )
    )
    second = op_sum(
        *(
            op_scale(
                MTWO * EPS_UP[up][b],
                lambda p, b=b: theta_squared(dt(b, p)),
            )
            for b in range(2)
        )
    )
    return op_sum(first, second)


S = tuple(s_op(a) for a in range(2))


def test_inputs() -> tuple[Poly, ...]:
    exponents = tuple(values for values in product(range(3), repeat=4) if sum(values) <= 2)
    return tuple(basis(mask, values) for mask in range(4) for values in exponents)


CASES = test_inputs()
failures: list[str] = []
families: dict[str, dict[str, int]] = {}


def check(family: str, label: str, left, right=zero) -> None:
    record = families.setdefault(
        family,
        {"operator_identities": 0, "input_cases": 0, "failed_cases": 0},
    )
    record["operator_identities"] += 1
    record["input_cases"] += len(CASES)
    for case_index, value in enumerate(CASES):
        left_value = norm(left(value))
        right_value = norm(right(value))
        if left_value != right_value:
            record["failed_cases"] += 1
            failures.append(
                f"{family}:{label}:case={case_index}:left={left_value}:right={right_value}"
            )


# Odd brackets and the Poincare/special-conformal mixed sectors.
for a in range(2):
    for dot in range(2):
        check(
            "euclidean_graded_algebra",
            f"QQbar[{a},{dot}]",
            anti(Q[a], BQ[dot]),
            linear((MTWO * SIGE[m][a][dot], P[m]) for m in range(4)),
        )
        check("euclidean_graded_algebra", f"QbarS[{a},{dot}]", anti(Q[a], BS[dot]))
        check("euclidean_graded_algebra", f"barQS[{dot},{a}]", anti(BQ[dot], S[a]))
        check(
            "euclidean_graded_algebra",
            f"SbarS[{a},{dot}]",
            anti(S[a], BS[dot]),
            linear((MTWO * BSIGE[m][dot][a], K[m]) for m in range(4)),
        )

for a in range(2):
    check("euclidean_dilation_r", f"DQ[{a}]", comm(DIL, Q[a]), op_scale(HALF, Q[a]))
    check("euclidean_dilation_r", f"RQ[{a}]", comm(R, Q[a]), op_scale(I, Q[a]))
    check("euclidean_dilation_r", f"DS[{a}]", comm(DIL, S[a]), op_scale(C(Fraction(-1, 2)), S[a]))
    check("euclidean_dilation_r", f"RS[{a}]", comm(R, S[a]), op_scale(MI, S[a]))
    for m in range(4):
        check(
            "euclidean_mixed_even_odd",
            f"KQ[{m},{a}]",
            comm(K[m], Q[a]),
            linear((SIGE[m][a][dot], BS[dot]) for dot in range(2)),
        )
        check(
            "euclidean_mixed_even_odd",
            f"PS[{m},{a}]",
            comm(P[m], S[a]),
            linear((-BSIGE[m][dot][a], BQ[dot]) for dot in range(2)),
        )
    for b in range(2):
        rhs_terms = [
            (C(-2) if a == b else Z, DIL),
            (C(0, -3) if a == b else Z, R),
        ]
        for m in range(4):
            for n in range(4):
                rhs_terms.append((MI * TWO * SIGEMN[m, n][a][b], J[m, n]))
        check(
            "euclidean_graded_algebra",
            f"QS[{a},{b}]",
            anti(Q[a], S[b]),
            linear(rhs_terms),
        )

for dot in range(2):
    check("euclidean_dilation_r", f"DbarQ[{dot}]", comm(DIL, BQ[dot]), op_scale(HALF, BQ[dot]))
    check("euclidean_dilation_r", f"RbarQ[{dot}]", comm(R, BQ[dot]), op_scale(MI, BQ[dot]))
    check("euclidean_dilation_r", f"DbarS[{dot}]", comm(DIL, BS[dot]), op_scale(C(Fraction(-1, 2)), BS[dot]))
    check("euclidean_dilation_r", f"RbarS[{dot}]", comm(R, BS[dot]), op_scale(I, BS[dot]))
    for m in range(4):
        check(
            "euclidean_mixed_even_odd",
            f"PbarS[{m},{dot}]",
            comm(P[m], BS[dot]),
            linear((BSIGE[m][dot][a], Q[a]) for a in range(2)),
        )
        check(
            "euclidean_mixed_even_odd",
            f"KbarQ[{m},{dot}]",
            comm(K[m], BQ[dot]),
            linear((-SIGE[m][a][dot], S[a]) for a in range(2)),
        )
    for other in range(2):
        rhs_terms = [
            (C(2) if dot == other else Z, DIL),
            (C(0, -3) if dot == other else Z, R),
        ]
        for m in range(4):
            for n in range(4):
                rhs_terms.append((MI * TWO * BAREMN[m, n][other][dot], J[m, n]))
        check(
            "euclidean_graded_algebra",
            f"barQbarS[{dot},{other}]",
            anti(BQ[dot], BS[other]),
            linear(rhs_terms),
        )

# Bosonic conformal algebra.
for m in range(4):
    check("euclidean_bosonic_conformal", f"DP[{m}]", comm(DIL, P[m]), P[m])
    check("euclidean_bosonic_conformal", f"DK[{m}]", comm(DIL, K[m]), op_scale(M, K[m]))
    for n in range(4):
        check(
            "euclidean_bosonic_conformal",
            f"PK[{m},{n}]",
            comm(P[m], K[n]),
            linear(((TWO if m == n else Z, DIL), (C(0, 2), J[m, n]))),
        )

for a in range(2):
    for b in range(2):
        check("euclidean_graded_algebra", f"QQ[{a},{b}]", anti(Q[a], Q[b]))
        check("euclidean_graded_algebra", f"SS[{a},{b}]", anti(S[a], S[b]))
for dot in range(2):
    for other in range(2):
        check("euclidean_graded_algebra", f"barQbarQ[{dot},{other}]", anti(BQ[dot], BQ[other]))
        check("euclidean_graded_algebra", f"barSbarS[{dot},{other}]", anti(BS[dot], BS[other]))

for m in range(4):
    check("euclidean_zero_sectors", f"RP[{m}]", comm(R, P[m]))
    check("euclidean_zero_sectors", f"RK[{m}]", comm(R, K[m]))
    for n in range(4):
        check("euclidean_zero_sectors", f"PP[{m},{n}]", comm(P[m], P[n]))
        check("euclidean_zero_sectors", f"KK[{m},{n}]", comm(K[m], K[n]))
    for a in range(2):
        check("euclidean_zero_sectors", f"PQ[{m},{a}]", comm(P[m], Q[a]))
        check("euclidean_zero_sectors", f"KS[{m},{a}]", comm(K[m], S[a]))
    for dot in range(2):
        check("euclidean_zero_sectors", f"PbarQ[{m},{dot}]", comm(P[m], BQ[dot]))
        check("euclidean_zero_sectors", f"KbarS[{m},{dot}]", comm(K[m], BS[dot]))

check("euclidean_zero_sectors", "DR", comm(DIL, R))

# Spin(4) action on all generators and the complete rotation algebra.
for m in range(4):
    for n in range(4):
        check("euclidean_spin4", f"DJ[{m},{n}]", comm(DIL, J[m, n]))
        check("euclidean_spin4", f"RJ[{m},{n}]", comm(R, J[m, n]))
        for a in range(2):
            check(
                "euclidean_spin4",
                f"JQ[{m},{n},{a}]",
                comm(J[m, n], Q[a]),
                linear((I * SIGEMN[m, n][a][b], Q[b]) for b in range(2)),
            )
            check(
                "euclidean_spin4",
                f"JS[{m},{n},{a}]",
                comm(J[m, n], S[a]),
                linear((MI * SIGEMN[m, n][b][a], S[b]) for b in range(2)),
            )
        for dot in range(2):
            check(
                "euclidean_spin4",
                f"JbarQ[{m},{n},{dot}]",
                comm(J[m, n], BQ[dot]),
                linear((MI * BAREMN[m, n][other][dot], BQ[other]) for other in range(2)),
            )
            check(
                "euclidean_spin4",
                f"JbarS[{m},{n},{dot}]",
                comm(J[m, n], BS[dot]),
                linear((I * BAREMN[m, n][dot][other], BS[other]) for other in range(2)),
            )
        for r in range(4):
            check(
                "euclidean_spin4",
                f"JP[{m},{n},{r}]",
                comm(J[m, n], P[r]),
                linear(
                    (
                        (I if r == m else Z, P[n]),
                        (MI if r == n else Z, P[m]),
                    )
                ),
            )
            check(
                "euclidean_spin4",
                f"JK[{m},{n},{r}]",
                comm(J[m, n], K[r]),
                linear(
                    (
                        (I if r == m else Z, K[n]),
                        (MI if r == n else Z, K[m]),
                    )
                ),
            )
        for r in range(4):
            for s in range(4):
                check(
                    "euclidean_spin4",
                    f"JJ[{m},{n},{r},{s}]",
                    comm(J[m, n], J[r, s]),
                    linear(
                        (
                            (I if r == m else Z, J[n, s]),
                            (MI if r == n else Z, J[m, s]),
                            (MI if s == m else Z, J[n, r]),
                            (I if s == n else Z, J[m, r]),
                        )
                    ),
                )


# Wick-transported Lorentzian realization on the same Euclidean polynomial basis.
ETA = (-1, 1, 1, 1)
SIGL = (SID, S1, S2, S3)
BSIGL = (SID, mscale(M, S1), mscale(M, S2), mscale(M, S3))
SIGL_LOWER = tuple(mscale(C(ETA[mu]), SIGL[mu]) for mu in range(4))
SIGLMN: dict[tuple[int, int], Matrix] = {}
for mu in range(4):
    for nu in range(4):
        SIGLMN[mu, nu] = mscale(
            C(Fraction(1, 4)),
            msub(mm(SIGL[mu], BSIGL[nu]), mm(SIGL[nu], BSIGL[mu])),
        )


def ly(mu: int, p: Poly) -> Poly:
    if mu == 0:
        return scale(MI, mul_y(3, p))
    return mul_y(mu - 1, p)


def ldy(mu: int, p: Poly) -> Poly:
    if mu == 0:
        return scale(I, dy(3, p))
    return dy(mu - 1, p)


def ly_then_ldy(mu: int, nu: int):
    return lambda p: ly(mu, ldy(nu, p))


LE = op_sum(*(ly_then_ldy(mu, mu) for mu in range(4)))
LP = tuple(op_scale(MI, lambda p, mu=mu: ldy(mu, p)) for mu in range(4))
LQ = tuple(op_scale(MI, lambda p, a=a: dt(a, p)) for a in range(2))
LBQ = tuple(
    op_sum(
        *(
            op_scale(
                MTWO * SIGL[mu][a][dot],
                lambda p, a=a, mu=mu: mul_t(a, ldy(mu, p)),
            )
            for a in range(2)
            for mu in range(4)
        )
    )
    for dot in range(2)
)
LDIL = op_scale(MI, op_sum(LE, op_scale(HALF, N)))
LR = N


def l_rotation(mu: int, nu: int):
    orbital = op_scale(
        MI,
        op_sum(
            op_scale(C(ETA[mu]), ly_then_ldy(mu, nu)),
            op_scale(C(-ETA[nu]), ly_then_ldy(nu, mu)),
        ),
    )
    sigma_lower = mscale(C(ETA[mu] * ETA[nu]), SIGLMN[mu, nu])
    spin = op_sum(
        *(
            op_scale(I * sigma_lower[a][b], t_then_d(a, b))
            for a in range(2)
            for b in range(2)
        )
    )
    return op_sum(orbital, spin)


LJ = {(mu, nu): l_rotation(mu, nu) for mu in range(4) for nu in range(4)}


def l_y_squared_then_d(mu: int):
    return op_sum(
        *(
            op_scale(
                C(ETA[rho]),
                lambda p, rho=rho, mu=mu: ly(rho, ly(rho, ldy(mu, p))),
            )
            for rho in range(4)
        )
    )


def l_tilde_y_entry(dot: int, a: int, p: Poly) -> Poly:
    return add(
        *(
            scale(C(ETA[nu]) * BSIGL[nu][dot][a], ly(nu, p))
            for nu in range(4)
        )
    )


def l_k_op(mu: int):
    bosonic = op_sum(
        l_y_squared_then_d(mu),
        op_scale(C(-2 * ETA[mu]), lambda p, mu=mu: ly(mu, LE(p))),
    )
    spin = op_sum(
        *(
            op_scale(
                SIGL_LOWER[mu][b][dot],
                lambda p, b=b, a=a, dot=dot: mul_t(
                    b,
                    l_tilde_y_entry(dot, a, dt(a, p)),
                ),
            )
            for b in range(2)
            for a in range(2)
            for dot in range(2)
        )
    )
    return op_scale(MI, op_sum(bosonic, spin))


LK = tuple(l_k_op(mu) for mu in range(4))
LBS = tuple(
    op_sum(
        *(lambda p, dot=dot, a=a: l_tilde_y_entry(dot, a, dt(a, p)) for a in range(2))
    )
    for dot in range(2)
)


def l_s_op(up: int):
    first = op_sum(
        *(
            op_scale(
                C(0, 2) * SIGL[mu][b][dot],
                lambda p, b=b, mu=mu, dot=dot, up=up: mul_t(
                    b,
                    l_tilde_y_entry(dot, up, ldy(mu, p)),
                ),
            )
            for b in range(2)
            for mu in range(4)
            for dot in range(2)
        )
    )
    second = op_sum(
        *(
            op_scale(
                C(0, -2) * EPS_UP[up][b],
                lambda p, b=b: theta_squared(dt(b, p)),
            )
            for b in range(2)
        )
    )
    return op_sum(first, second)


LS = tuple(l_s_op(a) for a in range(2))

vector_wick = ((0, 1, MI), (1, 2, MI), (2, 3, MI), (3, 0, M))
for m, mu, phase in vector_wick:
    check("wick_phase_relations", f"P_E[{m}]", P[m], op_scale(phase, LP[mu]))
    check("wick_phase_relations", f"K_E[{m}]", K[m], op_scale(phase, LK[mu]))
for a in range(2):
    check("wick_phase_relations", f"Q_E[{a}]", Q[a], op_scale(MI, LQ[a]))
    check("wick_phase_relations", f"S_E[{a}]", S[a], op_scale(MI, LS[a]))
for dot in range(2):
    check("wick_phase_relations", f"barQ_E[{dot}]", BQ[dot], op_scale(MI, LBQ[dot]))
    check("wick_phase_relations", f"barS_E[{dot}]", BS[dot], op_scale(MI, LBS[dot]))
check("wick_phase_relations", "D_E", DIL, op_scale(MI, LDIL))
check("wick_phase_relations", "R_E", R, op_scale(MI, LR))
for m in range(4):
    for n in range(4):
        if m == 3 and n < 3:
            mu, nu, phase = 0, n + 1, MI
        elif n == 3 and m < 3:
            mu, nu, phase = m + 1, 0, MI
        elif m < 3 and n < 3:
            mu, nu, phase = m + 1, n + 1, O
        else:
            mu, nu, phase = 0, 0, O
        check("wick_phase_relations", f"J_E[{m},{n}]", J[m, n], op_scale(phase, LJ[mu, nu]))


for record in families.values():
    record["passed_cases"] = record["input_cases"] - record["failed_cases"]

total_identities = sum(record["operator_identities"] for record in families.values())
total_input_cases = sum(record["input_cases"] for record in families.values())
total_failed_cases = sum(record["failed_cases"] for record in families.values())
audit = {
    "schema": 1,
    "task_id": "CONTRACT-STEP-02B-SUPERCONFORMAL-001",
    "signature": "Euclidean",
    "chart": "chiral (y_E^m,vartheta^a)",
    "arithmetic": "Q(i) polynomial coefficients and exact exterior algebra; no floating point; no CAS",
    "basis": {
        "grassmann_monomials": 4,
        "bosonic_monomials_total_degree_at_most_2": 15,
        "total_inputs": len(CASES),
    },
    "operator_definitions": {
        "P_m": "-partial_m",
        "Q_a": "-partial_a",
        "barQ_dot_a": "-2 vartheta sigma_E^m partial_m",
        "D": "-(y_E.partial_E+N_vartheta/2)",
        "R": "-i N_vartheta",
        "J_mn": "-i(y_m partial_n-y_n partial_m)-i vartheta sigma_E_mn partial_vartheta",
        "K_m": "-[(y^2 delta_m^n-2 y_m y^n)partial_n-vartheta(sigma_E_m tildeY_E)partial_vartheta]",
        "barS^dot_a": "tildeY_E^(dot a a) partial_a",
        "S^a": "-2 vartheta sigma_E^m tildeY_E^a partial_m-2 vartheta^2 epsilon^(ab)partial_b",
    },
    "wick_transport": {
        "coordinates": "y_L^0=-i y_E^4; y_L^i=y_E^i; vartheta_L=vartheta_E",
        "derivatives": "partial_L0=i partial_E4; partial_Li=partial_Ei",
        "scalar_and_spinor_phases": "G_E=-i G_L for G=D,R,Q,barQ,S,barS",
        "vector_phases": "G_Ei=-i G_Li and G_E4=-G_L0 for G=P,K",
        "rotation_phases": "J_Eij=J_Lij and J_E4i=-i J_L0i",
    },
    "families": families,
    "operator_identities": total_identities,
    "input_cases": total_input_cases,
    "failed_cases": total_failed_cases,
    "failures": failures,
    "status": "PASS" if not failures else "FAIL",
}

audit_path = Path(__file__).resolve().parents[1] / "audits" / "step2b-euclidean-superconformal-verification.json"
audit_path.write_text(json.dumps(audit, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(
    {
        "operator_identities": total_identities,
        "input_cases": total_input_cases,
        "failures": len(failures),
        "audit": str(audit_path),
    }
)
for failure in failures[:30]:
    print(failure)
raise SystemExit(1 if failures else 0)
